spring.application.name=EMS-backend
spring.datasource.url=jdbc:postgresql://ep-aged-sea-ap461hqh.c-7.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VDhi28owfxZU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}